# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

k_selection_cpp <- function(X, y, k, intercept = FALSE) {
    .Call(`_SUBLIME_k_selection_cpp`, X, y, k, intercept)
}

SRHT_cpp <- function(X, y, r) {
    .Call(`_SUBLIME_SRHT_cpp`, X, y, r)
}

